config/routes.rb
Reporty::Application.routes.draw do

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  controller :static_pages do
    get  'user_report' => :user_report
  end

  match  'user_report_list/:id' , to: 'admin#user_report_list', via: :get

  root "static_pages#index"

  resources :users

  resources :reports
  resources :admin

  match 'aprv', to: "admin#approve_report" , via: :post

  

end

app/views/admin/_added.erb
<%= @aprv.class %>

app/views/admin/approve_report.js.erb
//$("#get-checked").append("<%= escape_javascript( render 'admin/added' ) %>");

<% if @aprv ==  '1' %>

var $a = $("#rxqw<%= escape_javascript @report_id  %>");
$a.removeClass("warning").addClass("success");
//console.log( $("#rxqe<%= escape_javascript @report_id  %>").val());
$("#rxqe<%= escape_javascript @report_id  %>").val('0');
$("#rxqf<%= escape_javascript @report_id  %>").val("رفض");

<% else %>

var $a = $("#rxqw<%= escape_javascript @report_id  %>");
$a.removeClass("success").addClass("warning");
//console.log( $("#rxqe<%= escape_javascript @report_id  %>").val());
$("#rxqe<%= escape_javascript @report_id  %>").val('1');
$("#rxqf<%= escape_javascript @report_id  %>").val("موافقه");




<% end %>

app/views/admin/index.erb
<%= button_to 'خروج', logout_path, method: :delete, class: 'btn btn-default hidden-print'  %>

<br/>
<div> <!-- user info -->
  <h3 class="text-right"><%= @current_user.name %></h3>

</div> <!-- eof user info -->

<div>  <!-- toolbox -->
  <p class="text-right hidden-print">
    <!-- button type="button" -->
    <!--a class="btn btn-default" href="<%= new_user_path %>">
      مستخدم جديد
      <span class="glyphicon glyphicon-plus"></span>
    </a-->
    <a class="btn btn-default" href="<%= user_report_path %>">
      تقريري
      <span class="glyphicon glyphicon-plus"></span>
    </a>
    <a class="btn btn-default" href="<%= users_path %>">
      اداره المستخدمين
      <span class="glyphicon glyphicon-plus"></span>
    </a>


  </p>
</div><!-- eof toolbox -->


<div> <!-- reports info -->


  <table class="table table-bordered table-striped text-right">
    <thead >
    <tr>
      <th class="text-right hidden-print">
        مراجعة
      </th>
      <th class="text-right hidden-print" > </th>
      <th class="text-right">
        اجمالي
      </th>
      <th class="text-right">
        الاسم
      </th>
    </tr>
    </thead>
    <tbody>

    <% @users.each do |u| %>
        <% @aprv_count = Report.where(user_id: u.id, approved: false).count %>
        <% if @aprv_count.to_i > 0  %>
            <tr class="danger">
        <% else %>
        <tr>
        <% end %>
          <td class="hidden-print"><%= @aprv_count %><%# u.get_total_hours.to_f - u.get_total_approved_hours %></td>
          <td class="hidden-print">
            <div class="progress ">
              <div class="progress-bar" role="progressbar" aria-valuenow="<%= u.get_total_approved_hours %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= u.get_total_approved_hours %>%;">
                <span class="sr-only"><%= u.get_total_approved_hours %>% Complete</span>
              </div>
            </div>
          </td>
          <td><%= u.get_total_approved_hours %></td>
          <td><%= link_to u.name, "/user_report_list/#{u.id}" %></td>
        </tr>
    <% end %>


    </tbody>
  </table>

</div> <!-- reports info -->

app/views/admin/user_report_list.erb
<%= link_to 'الصفحة الرئيسية', '/admin', class: 'btn btn-default hidden-print'  %>
<div> <!-- user info -->
  <h3 class="text-right"><%= @user.name %></h3>

 <div>
  <table class="table table-bordered table-striped text-right" >
    <thead >
        <tr >
          <th class="text-right">
             عدد
          </th>

          <th class="text-right">
            نوع اللقاء
          </th>
        </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        <%= @user_reports_type0.count.to_s  %>
      </td>
      <td>
          لقاءات الارشاد
      </td>
    </tr>
    <tr>
      <td>
        <%= @user_reports_type1.count.to_s  %>
      </td>
      <td>
         اجتماعات
      </td>
    </tr>
    <tr>
      <td>
        <%= @user_reports_type2.count.to_s  %>
      </td>
      <td>
          غياب
      </td>
    </tr>
    </tbody>
  </table>

 </div>

  <%= @user.get_total_approved_hours.to_s + "%" %>
  <div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="<%= @total_hours.to_i %>" aria-valuemin="0" aria-valuemax="100" style="width:<%= @total_hours.to_i %>%;">
      <span class="sr-only">60% Complete</span>
    </div>
  </div>
</div> <!-- eof user info -->

<div>  <!-- toolbox -->
  <p class="text-left hidden-print">
    <!-- button type="button" -->
    <%# link_to 'عوده', :back, class: 'btn btn-default hidden-print' %>

  </p>
</div><!-- eof toolbox -->

<% if @show == true %>
<div> <!-- reports info -->


  <table class="table table-bordered table-striped text-right">
    <thead >
    <tr>
      <th class="text-right hidden-print">
        ادوات
      </th>
      <th class="text-right">
        ملخص اللقاء
      </th>
      <th class="text-right">
        اجمالي
      </th>
      <th class="text-right">
        الساعه
      </th>
      <th class="text-right">
        اليوم والتاريخ
      </th>
    </tr>
    </thead>
    <tbody>


    <% @user_reports.each do |r| %>
        <tr class="<%=  set_status_approved r.approved %>" id="rxqw<%= r.id %>">
          <td class="hidden-print">
            <%# button_to 'delete', report_path(r.id), method: :delete, confirm: 'are you sure?' , class:'btn btn-link btn-sm space3' %>
            <%# link_to 'edit', edit_report_path(r.id) , class: 'btn btn-link btn-sm space3' %>

            <%= form_tag  '/aprv',remote: true, method: :post do %>
                <div class="field" id="start-time">
                  <%# check_box_tag :approved %>
                  <% if r.approved == true %>
                      <%= hidden_field_tag :approved, '0', id: "rxqe"+r.id.to_s %>
                  <% else %>
                     <%= hidden_field_tag :approved, '1', id: "rxqe"+r.id.to_s %>
                  <% end %>
                  <%= hidden_field_tag :user_id, r.user_id  %>
                  <%= hidden_field_tag :re_i, r.id  %>
                  <%= submit_tag approved_text(r), class:'btn btn-primary btn-sm ', id: "rxqf"+r.id.to_s  %>
                </div>
            <% end %>
            <ul class="space3">
                <li><%= button_to 'حذف', report_path(r.id), method: :delete, confirm: 'are you sure?' , class:'btn btn-link btn-sm  ' %></li>
                <li><%= link_to 'تعديل', edit_report_path(r.id) , class: 'btn btn-link btn-sm  ' %></li>
            </ul>
            <%# button_to 'ok', {action: :approve_report ,remote: true, method: :post } , data:{approved: true, user_id: r.user_id}, class:'btn btn-primary'  %>
            <%# link_to 'ok' ,'/aprv' ,remote: true , data:{approved: true, user_id: r.user_id}, method: :post, class:'btn btn-primary appr' %>
          </td>
          <td><%= r.description %></td>
          <td><%= r.total_hours %></td>
          <td><%=  format_time_view(r.end_time) + " <-- " +  format_time_view(r.start_time)   %></td>
          <td><%= r.day.day_name.to_s  + "  "  + r.day.to_s  %></td>

        </tr>

    <% end %>

    </tbody>
  </table>

</div> <!-- reports info -->

   <% end %>

<% if @user_reports_type0.count > 0 %>
<div> <!-- reports info  type0 -->
  <h3 class="text-right"><%= @user_reports_type0.count.to_s +  '  لقاءات الارشاد' %></h3>


  <table class="table table-bordered table-striped text-right">
    <thead >
    <tr>
      <th class="text-right hidden-print">
        ادوات
      </th>
      <th class="text-right">
        ملخص اللقاء
      </th>
      <th class="text-right">
        اجمالي
      </th>
      <th class="text-right">
        الساعه
      </th>
      <th class="text-right">
        اليوم والتاريخ
      </th>
    </tr>
    </thead>
    <tbody>


    <% @user_reports_type0.each do |r| %>
        <tr class="<%=  set_status_approved r.approved %>" id="rxqw<%= r.id %>">
          <td class="hidden-print">
            <%# button_to 'delete', report_path(r.id), method: :delete, confirm: 'are you sure?' , class:'btn btn-link btn-sm space3' %>
            <%# link_to 'edit', edit_report_path(r.id) , class: 'btn btn-link btn-sm space3' %>

            <%= form_tag  '/aprv',remote: true, method: :post do %>
                <div class="field" id="start-time">
                  <%# check_box_tag :approved %>
                  <% if r.approved == true %>
                      <%= hidden_field_tag :approved, '0', id: "rxqe"+r.id.to_s %>
                  <% else %>
                      <%= hidden_field_tag :approved, '1', id: "rxqe"+r.id.to_s %>
                  <% end %>
                  <%= hidden_field_tag :user_id, r.user_id  %>
                  <%= hidden_field_tag :re_i, r.id  %>
                  <%= submit_tag approved_text(r), class:'btn btn-primary btn-sm ', id: "rxqf"+r.id.to_s  %>
                </div>
            <% end %>
            <ul class="space3">
              <li><%= button_to 'حذف', report_path(r.id), method: :delete, confirm: 'are you sure?' , class:'btn btn-link btn-sm  ' %></li>
              <li><%= link_to 'تعديل', edit_report_path(r.id) , class: 'btn btn-link btn-sm  ' %></li>
            </ul>
            <%# button_to 'ok', {action: :approve_report ,remote: true, method: :post } , data:{approved: true, user_id: r.user_id}, class:'btn btn-primary'  %>
            <%# link_to 'ok' ,'/aprv' ,remote: true , data:{approved: true, user_id: r.user_id}, method: :post, class:'btn btn-primary appr' %>
          </td>
          <td><%= r.description %></td>
          <td><%= r.total_hours %></td>
          <td><%=  format_time_view(r.end_time) + " <-- " +  format_time_view(r.start_time)   %></td>
          <td><%= r.day.day_name.to_s  + "  "  + r.day.to_s  %></td>

        </tr>

    <% end %>

    </tbody>
  </table>

</div> <!-- reports info -->
<% end %>

<% if @user_reports_type1.count > 0 %>
<div> <!-- reports info -->
  <h3 class="text-right"><%= @user_reports_type1.count.to_s +  '  اجتماعات' %></h3>


  <table class="table table-bordered table-striped text-right">
    <thead >
    <tr>
      <th class="text-right hidden-print">
        ادوات
      </th>
      <th class="text-right">
        ملخص اللقاء
      </th>
      <th class="text-right">
        اجمالي
      </th>
      <th class="text-right">
        الساعه
      </th>
      <th class="text-right">
        اليوم والتاريخ
      </th>
    </tr>
    </thead>
    <tbody>


    <% @user_reports_type1.each do |r| %>
        <tr class="<%=  set_status_approved r.approved %>" id="rxqw<%= r.id %>">
          <td class="hidden-print">
            <%# button_to 'delete', report_path(r.id), method: :delete, confirm: 'are you sure?' , class:'btn btn-link btn-sm space3' %>
            <%# link_to 'edit', edit_report_path(r.id) , class: 'btn btn-link btn-sm space3' %>

            <%= form_tag  '/aprv',remote: true, method: :post do %>
                <div class="field" id="start-time">
                  <%# check_box_tag :approved %>
                  <% if r.approved == true %>
                      <%= hidden_field_tag :approved, '0', id: "rxqe"+r.id.to_s %>
                  <% else %>
                      <%= hidden_field_tag :approved, '1', id: "rxqe"+r.id.to_s %>
                  <% end %>
                  <%= hidden_field_tag :user_id, r.user_id  %>
                  <%= hidden_field_tag :re_i, r.id  %>
                  <%= submit_tag approved_text(r), class:'btn btn-primary btn-sm ', id: "rxqf"+r.id.to_s  %>
                </div>
            <% end %>
            <ul class="space3">
              <li><%= button_to 'حذف', report_path(r.id), method: :delete, confirm: 'are you sure?' , class:'btn btn-link btn-sm  ' %></li>
              <li><%= link_to 'تعديل', edit_report_path(r.id) , class: 'btn btn-link btn-sm  ' %></li>
            </ul>
            <%# button_to 'ok', {action: :approve_report ,remote: true, method: :post } , data:{approved: true, user_id: r.user_id}, class:'btn btn-primary'  %>
            <%# link_to 'ok' ,'/aprv' ,remote: true , data:{approved: true, user_id: r.user_id}, method: :post, class:'btn btn-primary appr' %>
          </td>
          <td><%= r.description %></td>
          <td><%= r.total_hours %></td>
          <td><%=  format_time_view(r.end_time) + " <-- " +  format_time_view(r.start_time)   %></td>
          <td><%= r.day.day_name.to_s  + "  "  + r.day.to_s  %></td>

        </tr>

    <% end %>

    </tbody>
  </table>

</div> <!-- reports info -->
<% end %>

<% if @user_reports_type2.count > 0 %>
<div> <!-- reports info -->
  <h3 class="text-right"><%= @user_reports_type2.count.to_s +  '  غياب' %></h3>


  <table class="table table-bordered table-striped text-right">
    <thead >
    <tr>
      <th class="text-right hidden-print">
        ادوات
      </th>
      <th class="text-right">
        ملخص اللقاء
      </th>
      <th class="text-right">
        اجمالي
      </th>
      <th class="text-right">
        الساعه
      </th>
      <th class="text-right">
        اليوم والتاريخ
      </th>
    </tr>
    </thead>
    <tbody>


    <% @user_reports_type2.each do |r| %>
        <tr class="<%=  set_status_approved r.approved %>" id="rxqw<%= r.id %>">
          <td class="hidden-print">
            <%# button_to 'delete', report_path(r.id), method: :delete, confirm: 'are you sure?' , class:'btn btn-link btn-sm space3' %>
            <%# link_to 'edit', edit_report_path(r.id) , class: 'btn btn-link btn-sm space3' %>

            <%= form_tag  '/aprv',remote: true, method: :post do %>
                <div class="field" id="start-time">
                  <%# check_box_tag :approved %>
                  <% if r.approved == true %>
                      <%= hidden_field_tag :approved, '0', id: "rxqe"+r.id.to_s %>
                  <% else %>
                      <%= hidden_field_tag :approved, '1', id: "rxqe"+r.id.to_s %>
                  <% end %>
                  <%= hidden_field_tag :user_id, r.user_id  %>
                  <%= hidden_field_tag :re_i, r.id  %>
                  <%= submit_tag approved_text(r), class:'btn btn-primary btn-sm ', id: "rxqf"+r.id.to_s  %>
                </div>
            <% end %>
            <ul class="space3">
              <li><%= button_to 'حذف', report_path(r.id), method: :delete, confirm: 'are you sure?' , class:'btn btn-link btn-sm  ' %></li>
              <li><%= link_to 'تعديل', edit_report_path(r.id) , class: 'btn btn-link btn-sm  ' %></li>
            </ul>
            <%# button_to 'ok', {action: :approve_report ,remote: true, method: :post } , data:{approved: true, user_id: r.user_id}, class:'btn btn-primary'  %>
            <%# link_to 'ok' ,'/aprv' ,remote: true , data:{approved: true, user_id: r.user_id}, method: :post, class:'btn btn-primary appr' %>
          </td>
          <td><%= r.description %></td>
          <td><%= r.total_hours %></td>
          <td><%=  format_time_view(r.end_time) + " <-- " +  format_time_view(r.start_time)   %></td>
          <td><%= r.day.day_name.to_s  + "  "  + r.day.to_s  %></td>

        </tr>

    <% end %>

    </tbody>
  </table>

</div> <!-- reports info -->

<% end %>