config/routes.rb
Reporty::Application.routes.draw do

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  controller :static_pages do
    get  'user_report' => :user_report
  end

  match  'user_report_list/:id' , to: 'admin#user_report_list', via: :get

  root "static_pages#index"

  resources :users

  resources :reports
  resources :admin

  match 'aprv', to: "admin#approve_report" , via: :post

  

end

app/models/report.rb
class Report < ActiveRecord::Base


  belongs_to :user

  before_save :update_total_hours
  before_save :update_meeting_type

  validates :start_time, :end_time, :day, presence: true


  validates :description, length: { maximum: 255 }


  private
  def update_total_hours

    hours = end_time.hour - start_time.hour
    minutes  = end_time.min - start_time.min

    if ( hours < 0 or minutes < 0)
      self.end_time = self.start_time
      hours = 0
      minutes  = 0
    end

    self.total_hours = hours + (minutes.to_f/60.0)

  end

  def update_meeting_type
    if self.meeting_type == 2
     self.end_time = self.start_time
     self.total_hours = 0
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :is_admin, only: [:index,:edit, :update, :destroy,:show]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to user_report_path, notice: 'تم الحفظ بنجاح' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to "/user_report_list/#{@report.user_id.to_s}" , notice: 'تم التعديل بنجاح' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id] )
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:start_time, :end_time, :description, :day, :total_hours, :user_id, :approved, :meeting_type)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper

  def fix_minutes_view min
    (min.to_i < 10) ? min.to_s + '0' : min
  end
end

app/views/reports/_approv.erb
<%= form_for(Report.find())  do |f| %>


    <div class="field" id="start-time">
      <%= f.label :approved  %><br>
      <%= f.check_box :approved %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/reports/_form.html.erb
<%= form_for(@report)  do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <div class="text-center">
  <div class="field" id="start-time">

    <%= f.time_select :start_time, {minute_step:15} %>
    <%= f.label :start_time, 'ساعة البدايه' %>
  </div>
  <div class="field row" id="end-time">

    <%= f.time_select :end_time, {minute_step:15} %>
    <%= f.label :end_time, 'ساعة النهايه' %>
  </div>
    <div class="field ">

      <%= f.date_select :day,{end_year: 2014, start_year: 2013}  %>
      <%= f.label :day, 'التاريخ' %>
    </div>

  <div class="field row">
    <%= f.label :description, 'محتوى اللقاء' %> <br />
    <%= f.select  :meeting_type, [['ارشاد','0'],['اجتماع','1'], ['غياب','2']]  %>   <br /> <br />
    <%= f.text_area :description, size: "20x10" , class: "text-right ", maxlength: 255  %>
  </div>


    <div class="field">
      <%= f.hidden_field :user_id, value: session[:user_id] %>
    </div>





  <div class="actions">
    <%= f.submit 'حفظ',class: 'btn btn-primary' %>
  </div>

    </div>
<% end %>

app/views/reports/edit.html.erb
<h3 class="text-center">تعديل التقرير</h3>
<%= link_to 'عوده', :back, class: 'btn btn-default hidden-print' %>
<%= render 'form' %>

<%# link_to 'Show', @report %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Description</th>
      <th>Day</th>
      <th>Total hours</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.start_time.hour %>:<%=  fix_minutes_view report.start_time.min %> </td>
        <td><%= report.end_time.hour %>:<%= fix_minutes_view report.end_time.min  %></td>
        <td><%= report.description %></td>
        <td><%= report.day %></td>
        <td><%= report.total_hours %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h3 class="text-center">تقرير جديد</h3>
<%= link_to 'عوده', :back, class: 'btn btn-default hidden-print' %>

<%= render 'form' %>

<%# link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @report.start_time.hour %>:<%= fix_minutes_view @report.start_time.min.to_i  %>
</p>

<p>
  <strong>End time:</strong>
  <%= @report.end_time.hour %>:<%= fix_minutes_view @report.end_time.min  %>
</p>

<p>
  <strong>Description:</strong>
  <%= @report.description %>
</p>

<p>
  <strong>Day:</strong>
  <%= @report.day %>
</p>

<p>
  <strong>Total hours:</strong>
  <%= @report.total_hours %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>